
name: Task_5_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-18.04
    env:
      DB_DATABASE: test_db
      DB_USER: user
      DB_PASSWORD: user

    steps:
      - name: checkout_master_branch
        uses: actions/checkout@v2
       
      - name: Set up MySQL
        run: |
         sudo /etc/init.d/mysql start
         mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u root -p
         mysql ${{ env.DB_DATABASE }} < /home/runner/work/Task5/Task5/CREATE.sql -u root -p
         mysql -e 'USE ${{ env.DB_DATABASE }}; SHOW TABLES;' -u root -p
  #-p ${{ env.DB_PASSWORD }}
  build:
    needs: db
    runs-on: ubuntu-18.04
    steps:
      - name: checkout_master_branch
        uses: actions/checkout@v2

      - name: setup_jdk
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: build_java_with_maven
        run: mvn -B package --file pom.xml
        
      - run: ls -a
      - run: |
          cd target,
          ls -a
