
name: Task_5

on:
  push:
    branches: [ master ]

jobs:
  mysql:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: mydb
      DB_USER: root
      DB_PASSWORD: root


    steps:
      - uses: actions/checkout@v2
               
      - run: |
         sudo /etc/init.d/mysql start
         mysql -e 'CREATE DATABASE mydb;' -uroot -proot
         mysql mydb < CREATE.sql -uroot -proot

  java:
    needs: mysql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        

      - uses: actions/setup-java@v1
        with:
            java-version: 8.0

      - run: mvn package -P init-base
        
        
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-jar
          path: target
