
name: Task_5_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-18.04
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: checkout_master_branch
        uses: actions/checkout@v2
       
      - name: Set up MySQL
        run: |
         ls -a /home/runner/work/Task5/Task5
         sudo /etc/init.d/mysql start
         mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
         mysql -u ${{ env.DB_USER }} ${{ env.DB_DATABASE }} < CREATE.sql
         mysql -e 'USE ${{ env.DB_DATABASE }}; SHOW TABLES;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

  build:
    needs: db
    runs-on: ubuntu-18.04
    steps:
      - name: checkout_master_branch
        uses: actions/checkout@v2

      - name: setup_jdk
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: build_java_with_maven
        run: mvn -B package --file pom.xml
        
      - run: ls -a
      - run: |
          cd target,
          ls -a
