
name: Task_5

on:
  push:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: mydb
      DB_USER: root
      DB_PASSWORD: root


    steps:
      - uses: actions/checkout@v2
               
      - run: |
         sudo /etc/init.d/mysql start
         mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
         mysql ${{ env.DB_DATABASE }} < CREATE.sql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

  build:
    needs: db
    runs-on: ubuntu-latest
    steps:
      - name: checkout_master_branch
        uses: actions/checkout@v2

      - name: setup_jdk
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: build_java_with_maven
        run: mvn package -P init-base
        
      - name: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: target/*.jar
