
name: Task_5_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  db:
    runs-on: ubuntu-latest
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql user: 'user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: user# Required if "mysql user" exists. The password for the "mysql user"

  build:
    needs: db
    runs-on: ubuntu-latest
    steps:
      - name: checkout_master_branch
        uses: actions/checkout@v2

      - name: setup_jdk
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: build_java_with_maven
        run: mvn -B package --file pom.xml
        
      - run: ls -a
      - run: |
          cd target,
          ls -a
